spring:
  application:
    name: challenge
  datasource: local
    driver-class-name: org.h2.Driver
    username: admin
    password: root
    url: "jdbc:h2:mem:challenge;DB_CLOSE_ON_EXIT=FALSE"
  #datasource:
  #  driver-class-name: org.postgresql.Driver
  #  url: jdbc:postgresql://ec2-54-227-248-71.compute-1.amazonaws.com
  #  username: khpinskznbmbgc
  #  password: bcc523d2135e6ac9415ebe871b01f9a47db12d499219bc928a0d9fb653ef2541
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    #database-platform: org.hibernate.dialect.H2Dialect
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
      lob:
          non_contextual_creation: 'true'
server:
  error:
    include-stacktrace: on_param
